---
settings:
  name: SaaS Backup For Partner Central
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn
sidebar:
  entries:
  - title: 파트너 센트럴
    entries:
    - title: NetApp SaaS Backup Partner Central 문서
      url: "/index.html"
    - title: 릴리스 정보
      entries:
      - title: 새로운 기능 및 업데이트
        url: "/partnercentral_reference_new.html"
      - title: 알려진 문제 및 제한 사항
        url: "/partnercentral_reference_limitations.html"
    - title: Partner Central에 등록하십시오
      url: "/partnercentral_task_register.html"
    - title: 고객을 추가하고 관리합니다
      url: "/partnercentral_task_add_and_manage_customers.html"
    - title: 고객 작업을 모니터링합니다
      url: "/partnercentral_task_monitor.html"
    - title: 보고서를 생성합니다
      url: "/partnercentral_task_generate_reports.html"
    - title: 설정을 관리합니다
      entries:
      - title: 알림을 관리합니다
        url: "/partnercentral_task_manage_notifications.html"
      - title: 역할을 관리합니다
        url: "/partnercentral_task_manage_roles.html"
      - title: 키 관리
        url: "/partnercentral_task_manage_keys.html"
    - title: 통계
      url: "/partnercentral_reference_statistics.html"
    - title: 도움을 받고 정보를 찾을 수 있는 곳
      url: "/partnercentral_reference_get_help_find_info.html"
